name: maliye_app
description: A new Flutter project.
publish_to: "none"
version: 1.5.0+15

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.1.0
  dio: ^3.0.10
  http_parser: any
  socket_io_client: ^2.0.0-beta.3

  # ui
  shared_preferences:
  url_launcher: ^6.0.3
  fluttertoast: ^8.0.6
  flutter_svg:
  infinite_scroll_pagination: ^2.2.1
  cached_network_image: ^2.3.2+1
  flutter_swiper: ^1.1.6
  file_picker: ^4.0.0
  circular_countdown_timer: ^0.2.0
  wakelock: ^0.5.2
  path_provider: ^2.0.2
  permission_handler: ^8.1.4+1
  open_file: ^3.2.1
  flutter_local_notifications: any
  intl: ^0.17.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/png/launch_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/png/
    - assets/svg/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 600
